version: "3"
services:
  cyberlux-cron:
    image: "cyberlux-cron:latest"
    restart: always
    ports:
      - "5001:5001"
    environment:
      DEBUG: "true"
      DB_HOSTNAME: "cyberlux-db"
      DB_NAME: "CYBERLUX"
      DB_USERNAME: "cyberlux"
      DB_PASSWORD: "cyberlux-pwd"
      JWT_SECRET_KEY: "some_random_secret"